# Packages and Libraries

- packages and libraries are Python files that contain collections ​of functions and global variables. 
- In NumPy, vectorization enables operations to be performed on multiple components of a data object at the same time.

​

# Numpy

- The only way to lengthen an array is to copy the existing array to a new memory address along with the new data.
- Adding a value of -1 in the designated new shape makes the process more efficient, as it indicates for NumPy to automatically infer the value based on other given values.


In [1]:
import numpy as np


np.full((5, 3), 8)

array([[8, 8, 8],
       [8, 8, 8],
       [8, 8, 8],
       [8, 8, 8],
       [8, 8, 8]])

In [2]:
array_2d = np.array([(1, 2, 3), (4, 5, 6)])
print(array_2d)
print()
array_2d.flatten()

[[1 2 3]
 [4 5 6]]



array([1, 2, 3, 4, 5, 6])

In [ ]:

array_2d = np.array([(1, 2, 3), (4, 5, 6)])
print(array_2d)
print()
array_2d.reshape(3, -1)

[[1 2 3]
 [4 5 6]]



array([[1, 2],
       [3, 4],
       [5, 6]])

In [4]:
array_2d = np.array([(1, 2, 3), (4, 5, 6)])
print(array_2d)
print()
array_2d.tolist()

[[1 2 3]
 [4 5 6]]



[[1, 2, 3], [4, 5, 6]]

In [5]:
print(array_2d.shape)
print(array_2d.dtype)
print(array_2d.size)
print(array_2d.T)

(2, 3)
int64
6
[[1 4]
 [2 5]
 [3 6]]


In [8]:
a = np.array([(1, 2, 3), (4, 5, 6)])
print(a)
print()

print(a[1])
print(a[0, 1])
print(a[1, 2])
print(a[:, 1:])

[[1 2 3]
 [4 5 6]]

[4 5 6]
2
6
[[2 3]
 [5 6]]
